name: Prettier

on:
    push:
        branches: [main]
        paths:
            - "domains/*"

jobs:
    format:
        name: Format
        runs-on: ubuntu-latest

        steps:
            - uses: actions/setup-node@v4
              with:
                  node-version: 20.x

            - name: Run Prettier
              run: npx -y prettier ./domains -w --tab-width 2 --print-width 120

            - name: Commit
              run: |
                  git config --global user.email "actions@github.com"
                  git config --global user.name "GitHub Actions"
                  git commit -am "Format domains"
                  git push
