name: Prettier

on:
    push:
        branches: [main]
        paths:
            - "domains/*"
            - ".github/workflows/prettier.yml"

jobs:
    format:
        name: Format
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 20.x

            - name: Run Prettier
              run: npx -y prettier ./domains -w --tab-width 2 --print-width 120

            - name: Create and switch to new branch
              run: |
                  BRANCH_NAME="prettier-$(date +%s)"
                  git checkout -b "$BRANCH_NAME"

            - name: Commit changes
              run: |
                  git config --local user.email "bot@is-a.dev"
                  git config --local user.name "is-a-dev-bot"
                  git add .
                  git commit -m "chore: apply Prettier formatting"

            - name: Push changes to new branch
              env:
                  API_TOKEN_GITHUB: ${{ secrets.BOT }}
              run: |
                  git push -u origin "$BRANCH_NAME"

            - name: Create Pull Request
              id: create_pr
              uses: peter-evans/create-pull-request@v5
              with:
                  token: ${{ secrets.BOT }}
                  head: "$BRANCH_NAME"
                  base: main
                  title: "$BRANCH_NAME"
                  body: "Generated from https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}."
                  auto-merge: true
