name: Prettier

on:
    push:
        branches: [main]
        paths:
            - "domains/*"
            - ".github/workflows/prettier.yml"

jobs:
    format:
        name: Format
        runs-on: ubuntu-latest

        steps:
            - uses: actions/setup-node@v4
              with:
                  node-version: 20.x

            - run: ls

            - name: Run Prettier
              run: npx -y prettier domains/*.json -w --tab-width 2 --print-width 120

            - name: Commit
              uses: cpina/github-action-push-to-another-repository@main
              with:
                  source-directory: "register"
                  destination-github-username: is-a-dev
                  destination-repository-name: register
                  user-email: "actions@github.com"
                  user-name: "GitHub Actions"
              env:
                  API_TOKEN_GITHUB: ${{ secrets.BOT }}
