name: Validation

on:
    pull_request:

    push:
        branches: [main]
        paths:
            - "domains/*"
            - "tests/*"
            - "utils/*"
            - ".github/workflows/validate.yml"
            - "dnsconfig.js"

    workflow_dispatch:

concurrency:
    group: ${{ github.ref }}-validation
    cancel-in-progress: true

jobs:
    dns:
        name: DNS
        if: "!contains(github.event.head_commit.message, '[skip-ci]')"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Check
              uses: is-a-dev/dnscontrol-action@main
              with:
                  args: check

    tests:
        name: Tests
        if: "!contains(github.event.head_commit.message, '[skip-ci]')"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - run: npm install

            - run: npm test
